# Generated by Django 4.2.7 on 2026-03-02 07:04

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('subscriber', 'Subscriber'), ('admin', 'Admin')], default='user', max_length=20)),
                ('subscription_type', models.CharField(choices=[('user', 'User'), ('subscriber', 'Subscriber'), ('admin', 'Admin')], default='user', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=20, unique=True)),
                ('company_name', models.TextField()),
                ('bse_scrip_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('sector', models.TextField(blank=True, db_index=True, null=True)),
                ('industry', models.TextField(blank=True, db_index=True, null=True)),
                ('index_name', models.TextField(blank=True, null=True)),
                ('no_of_employees', models.IntegerField(blank=True, null=True)),
                ('salary_to_median_employee_pay', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('peer_1_comp', models.TextField(blank=True, null=True)),
                ('peer_2_comp', models.TextField(blank=True, null=True)),
                ('peer_3_comp', models.TextField(blank=True, null=True)),
                ('peer_4_comp', models.TextField(blank=True, null=True)),
                ('peer_5_comp', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('director_code', models.CharField(max_length=25, unique=True)),
                ('director_name', models.TextField()),
                ('din', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('director_category', models.TextField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('promoter_status', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('key_flag', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='api.company')),
            ],
            options={
                'ordering': ['director_name'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('registration', 'Registration'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('data_access', 'Data Access'), ('selection_companies', 'Selection - Companies'), ('selection_directors', 'Selection - Directors'), ('error', 'Error')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DirectorRemuneration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('financial_year', models.CharField(max_length=10)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('pf_retirement', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('perquisites_allowances', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('bonus_commission', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('pay_excl_esops', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('esops', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('total_remuneration', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('options_granted', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fair_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('aggregate_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('remuneration_status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remunerations', to='api.director')),
            ],
            options={
                'ordering': ['-financial_year'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancials',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('financial_year', models.CharField(max_length=10)),
                ('total_income', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('pat', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('roa', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('employee_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('mcap', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='api.company')),
            ],
            options={
                'verbose_name_plural': 'Company Financials',
                'ordering': ['-financial_year'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_code'], name='api_company_company_8d6f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['sector'], name='api_company_sector_4a412e_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry'], name='api_company_industr_47505d_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_name'], name='api_company_company_a017bf_idx'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', '-timestamp'], name='api_useract_user_id_e5f544_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['activity_type', '-timestamp'], name='api_useract_activit_6b0b53_idx'),
        ),
        migrations.AddIndex(
            model_name='directorremuneration',
            index=models.Index(fields=['director', 'financial_year'], name='api_directo_directo_4f7361_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='directorremuneration',
            unique_together={('director', 'financial_year')},
        ),
        migrations.AddIndex(
            model_name='director',
            index=models.Index(fields=['director_code'], name='api_directo_directo_6841f5_idx'),
        ),
        migrations.AddIndex(
            model_name='director',
            index=models.Index(fields=['company'], name='api_directo_company_c89332_idx'),
        ),
        migrations.AddIndex(
            model_name='director',
            index=models.Index(fields=['director_name'], name='api_directo_directo_9acdd1_idx'),
        ),
        migrations.AddIndex(
            model_name='director',
            index=models.Index(fields=['din'], name='api_directo_din_751051_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfinancials',
            index=models.Index(fields=['company', 'financial_year'], name='api_company_company_b8146a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyfinancials',
            unique_together={('company', 'financial_year')},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='api_customu_email_3ba3be_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_staff'], name='api_customu_is_staf_9d1088_idx'),
        ),
    ]
