# Generated by Django 4.2.7 on 2026-01-21 10:16

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('subscriber', 'Subscriber'), ('admin', 'Admin')], default='user', max_length=20)),
                ('subscription_type', models.CharField(choices=[('user', 'User'), ('subscriber', 'Subscriber'), ('admin', 'Admin')], default='user', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('index', models.CharField(blank=True, max_length=64, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('director_id', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=128, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('promoter_status', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='api.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('registration', 'Registration'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('data_access', 'Data Access'), ('selection_companies', 'Selection - Companies'), ('selection_directors', 'Selection - Directors'), ('error', 'Error')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PeerComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_position', models.IntegerField(help_text='Peer position: 1, 2, 3, 4, or 5')),
                ('salary_to_median_emp_pay', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_comparisons', to='api.company')),
                ('peer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_in', to='api.company')),
            ],
            options={
                'ordering': ['company', 'peer_position'],
            },
        ),
        migrations.CreateModel(
            name='DirectorRemuneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_end_date', models.DateField(db_index=True)),
                ('fy_label', models.CharField(max_length=16)),
                ('basic_salary', models.FloatField(blank=True, null=True)),
                ('pf', models.FloatField(blank=True, null=True)),
                ('perqs', models.FloatField(blank=True, null=True)),
                ('bonus', models.FloatField(blank=True, null=True)),
                ('pay_excl_esops', models.FloatField(blank=True, null=True)),
                ('esops', models.FloatField(blank=True, null=True)),
                ('total_remuneration', models.FloatField(blank=True, null=True)),
                ('options_granted', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('fair_value', models.FloatField(blank=True, null=True)),
                ('aggregate_value', models.FloatField(blank=True, null=True)),
                ('remuneration_status', models.CharField(blank=True, max_length=256, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_remunerations', to='api.company')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remunerations', to='api.director')),
            ],
            options={
                'ordering': ['-fy_end_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_end_date', models.DateField(db_index=True)),
                ('fy_label', models.CharField(max_length=16)),
                ('total_income', models.FloatField(blank=True, null=True)),
                ('pat', models.FloatField(blank=True, null=True)),
                ('roa', models.FloatField(blank=True, null=True)),
                ('employee_cost', models.FloatField(blank=True, null=True)),
                ('mcap', models.FloatField(blank=True, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_timeseries', to='api.company')),
            ],
            options={
                'verbose_name_plural': 'Company Financial Time Series',
                'ordering': ['-fy_end_date'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['sector'], name='api_company_sector_4a412e_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry'], name='api_company_industr_47505d_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='api_company_name_35e8e7_idx'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', '-timestamp'], name='api_useract_user_id_e5f544_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['activity_type', '-timestamp'], name='api_useract_activit_6b0b53_idx'),
        ),
        migrations.AddIndex(
            model_name='peercomparison',
            index=models.Index(fields=['company'], name='api_peercom_company_1239c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='peercomparison',
            unique_together={('company', 'peer_company', 'peer_position')},
        ),
        migrations.AddIndex(
            model_name='directorremuneration',
            index=models.Index(fields=['company', 'fy_end_date'], name='api_directo_company_1e54a7_idx'),
        ),
        migrations.AddIndex(
            model_name='directorremuneration',
            index=models.Index(fields=['director', 'fy_end_date'], name='api_directo_directo_08b5b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='directorremuneration',
            unique_together={('company', 'director', 'fy_end_date')},
        ),
        migrations.AddIndex(
            model_name='director',
            index=models.Index(fields=['company'], name='api_directo_company_c89332_idx'),
        ),
        migrations.AddIndex(
            model_name='director',
            index=models.Index(fields=['name'], name='api_directo_name_a464ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='director',
            unique_together={('director_id', 'company')},
        ),
        migrations.AddIndex(
            model_name='companyfinancialtimeseries',
            index=models.Index(fields=['company', 'fy_end_date'], name='api_company_company_ba3bf3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyfinancialtimeseries',
            unique_together={('company', 'fy_end_date')},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='api_customu_email_3ba3be_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_staff'], name='api_customu_is_staf_9d1088_idx'),
        ),
    ]
