# Generated by Django 6.0 on 2025-12-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=128, null=True)),
                ('industry', models.CharField(blank=True, max_length=128, null=True)),
                ('index', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFinancialTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_end_date', models.DateField()),
                ('fy_label', models.CharField(max_length=16)),
                ('total_income', models.FloatField(blank=True, null=True)),
                ('pat', models.FloatField(blank=True, null=True)),
                ('roa', models.FloatField(blank=True, null=True)),
                ('employee_cost', models.FloatField(blank=True, null=True)),
                ('mcap', models.FloatField(blank=True, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'unique_together': {('company', 'fy_end_date')},
            },
        ),
        migrations.CreateModel(
            name='DirectorRemuneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_end_date', models.DateField()),
                ('fy_label', models.CharField(max_length=16)),
                ('basic_salary', models.FloatField(blank=True, null=True)),
                ('pf', models.FloatField(blank=True, null=True)),
                ('perqs', models.FloatField(blank=True, null=True)),
                ('bonus', models.FloatField(blank=True, null=True)),
                ('pay_excl_esops', models.FloatField(blank=True, null=True)),
                ('esops', models.FloatField(blank=True, null=True)),
                ('total_remuneration', models.FloatField(blank=True, null=True)),
                ('options_granted', models.FloatField(blank=True, null=True)),
                ('remuneration_status', models.CharField(blank=True, max_length=64, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.director')),
            ],
            options={
                'unique_together': {('company', 'director', 'fy_end_date')},
            },
        ),
    ]
