# Generated by Django 6.0 on 2025-12-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_director_companyfinancialtimeseries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorremuneration',
            name='remuneration_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
