# Generated by Django 4.2.7 on 2026-01-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_phone_unique'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='api_customu_subscri_a42d93_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='api_customu_email_3ba3be_idx',
            old_name='api_customu_email_12345678_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='api_useract_user_id_e5f544_idx',
            old_name='api_useract_user_id_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='api_useract_activit_6b0b53_idx',
            old_name='api_useract_activity_789012_idx',
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='api_customu_role_3dda3d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_superuser'], name='api_customu_is_supe_9c4b19_idx'),
        ),
    ]
